services:
  ros2_dev:
    build: .
    image: my_ros2_project:kilted
    container_name: ros2_kilted_dev
    network_mode: host # Важливо для Discovery в ROS 2
    ipc: host          # Для швидкої передачі даних між контейнерами
    privileged: true   # Потрібно для доступу до GPIO/USB на RPi
    volumes:
      - ./src:/ros2_ws/src
    environment:
      - ROS_DOMAIN_ID=42 # Щоб ваші комп'ютери "чули" один одного
    stdin_open: true
    tty: true
