services:
  ros2_dev:
    build: .
    image: rpi_ros2_project:jazzy
    container_name: ros2_jazy_rpi_dev
    network_mode: host # Важливо для Discovery в ROS 2
    ipc: host          # Для швидкої передачі даних між контейнерами
    privileged: true   # Потрібно для доступу до GPIO/USB на RPi
    group_add:
      - video
    volumes:
      - ./src:/ros2_ws/src
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - ROS_DOMAIN_ID=42 # Щоб ваші комп'ютери "чули" один одного
      - DISPLAY=${DISPLAY}
    devices:
      - "/dev/video0:/dev/video0"
      - "/dev/media3:/dev/media3"
    stdin_open: true
    tty: true
